# Site settings
title: Alex's Github Page
email: alexulrich@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Once I figure out some content to put here, I will update this description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://AlexUlrich.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  AlexUlrich

# Build settings
markdown: kramdown
